### ISSUE TITLE
Testing the understanding

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/GerbilQA-Benchmarking-Template#2]
@Berberer @rrichajalota @param-jot What do you guys think of the new template. Does it make sense?

**Comment by Berberer** [comment]
Looks good to me. Especially the simplification of creating an answer in the QALD format in the AbstractQASystem.

**Comment by RicardoUsbeck** [comment]
@Berberer it is a new version, please test it if time

**Comment by Berberer** [comment]
@RicardoUsbeck I tested the new version and encountered no problems integrating a custom QA system into the template. The new additions seem really helpful. 
A minor suggestion from my side to maybe improve the convenience of the template:
I think it would be helpful to add an ```onExit``` method or something like that to the ```AbstractQASystem``` that will be called when the system shuts down. For example when the programmer has to close connections properly or wants to write final statistics into a file that could be achieved with overriding the method and add the needed code.

**Comment by TortugaAttack** [comment]
The `onExit` method sounds good, I need to check how to do a shutdown hook in Spring though (`@PreDestroy` wont work in this instance). May @rrichajalota knows a way.

**Comment by rrichajalota** [comment]
@TortugaAttack Unfortunately, I don't know a way!

**Comment by TortugaAttack** [comment]
Close method will be called now if application is exited.
