### ISSUE TITLE
Current response doesn't comply with Gerbil's desired response format.

### ISSUE THREAD

**Issue by rrichajalota** [dice-group/GerbilQA-Benchmarking-Template#4]
When tested against Gerbil : http://gerbil-qa.aksw.org/gerbil/experiment?id=201801300000

**Current response**: 
```
{
	"questions": [{
		"question": [{
			"string": "What is the capital of Germany?",
			"language": "en"
		}],
		"answertype": "resource",
		"query": {
			"sparql": "SELECT ?s {?s ?p <http://example.com/prop/staticClass>} LIMIT 3"
		},
		"answers": [{
			"head": {
				"vars": ["resource"]
			},
			"results": {
				"bindings": [{
					"resource": {
						"type": "uri",
						"value": "http://example.com/res/static-1"
					}
				}, {
					"resource": {
						"type": "uri",
						"value": "http://example.com/res/static-3"
					}
				}, {
					"resource": {
						"type": "uri",
						"value": "http://example.com/res/static-2"
					}
				}]
			}
		}],
		"id": "1"
	}]
}
```
**Expected response**:
```
{
	"questions": [{
		"id": "1",
		"answertype": "resource",
		"question": [{
			"language": "en",
			"string": "What is the capital of Germany?"
		}],
		"query": {
			"sparql": "SELECT ?s {?s ?p <http://example.com/prop/staticClass>} LIMIT 3"
		},
		"answers": [{
			"head": {
				"vars": [
					"uri"
				]
			},
			"results": {
				"bindings": [{
						"uri": {
							"type": "uri",
							"value": "http://example.com/res/static-1"
						}
					},
					{
						"uri": {
							"type": "uri",
							"value": "http://example.com/res/static-2"
						}
					},
					{
						"uri": {
							"type": "uri",
							"value": "http://example.com/res/static-3"
						}
					}
				]
			}
		}]
	}]
}
```

**Comment by RicardoUsbeck** [comment]
Can you please try again? @rrichajalota ?

**Comment by rrichajalota** [comment]
@RicardoUsbeck I tried and it still gives the same error. http://gerbil-qa.aksw.org/gerbil/experiment?id=201802140002

**Comment by TortugaAttack** [comment]
where exactly is the difference? 
(Except from the different name of the variable?) 
Cannot see it :/

**Comment by TortugaAttack** [comment]
Okay, I diffed them and it seems the order is different (which should not be a problem as it is JSON) 
and the varname is different, which if this is the problem we have to change in either GerbilQA or qa.commons 
I will check for logs in Gerbil and see whats exactly wrong. ;)

**Comment by TortugaAttack** [comment]
Small Datasets works for me just fine. 
![screenshot-2018-2-15 http localhost](https://user-images.githubusercontent.com/5443313/36270986-8a41b294-127d-11e8-8d3c-2a56dee77113.png)

Maybe we do not have the most recent version of gerbil QA running?
If i remember correctly there was a bug fix recently with QALD WS which caused this. 
So basically we just need to update Gerbil QA to the last fix ;)

**Comment by RicardoUsbeck** [comment]
@MichaelRoeder :D ?

**Comment by MichaelRoeder** [comment]
Services has been updated and restarted. Please try again.

**Comment by TortugaAttack** [comment]
done. 
(tested it with localhost cause i did not want to forward a port on my flatmates network :D) 
![screenshot-2018-2-21 http localhost](https://user-images.githubusercontent.com/5443313/36498312-36deb3a2-173e-11e8-8518-eed8c737a504.png)
